// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nemesys_project.Context;

namespace nemesys_project.Migrations
{
    [DbContext(typeof(NemesysDbContext))]
    partial class NemesysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("nemesys_project.Models.Investigation", b =>
                {
                    b.Property<int>("InvestigationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfAction")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvestigatorId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("InvestigationId");

                    b.HasIndex("InvestigatorId");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("nemesys_project.Models.Investigator", b =>
                {
                    b.Property<int>("InvestigatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("InvestigatorId");

                    b.ToTable("Investigators");
                });

            modelBuilder.Entity("nemesys_project.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LatitudeLocation")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeLocation")
                        .HasColumnType("float");

                    b.Property<DateTime>("ProblemDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("ReporterInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UpVote")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("nemesys_project.Models.Reporter", b =>
                {
                    b.Property<int>("ReporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ReporterId");

                    b.ToTable("Reporters");
                });

            modelBuilder.Entity("nemesys_project.Models.Investigation", b =>
                {
                    b.HasOne("nemesys_project.Models.Report", "Report")
                        .WithOne("Investigation")
                        .HasForeignKey("nemesys_project.Models.Investigation", "InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nemesys_project.Models.Investigator", "Investigator")
                        .WithMany("Investigations")
                        .HasForeignKey("InvestigatorId");

                    b.Navigation("Investigator");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("nemesys_project.Models.Report", b =>
                {
                    b.HasOne("nemesys_project.Models.Reporter", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("nemesys_project.Models.Investigator", b =>
                {
                    b.Navigation("Investigations");
                });

            modelBuilder.Entity("nemesys_project.Models.Report", b =>
                {
                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("nemesys_project.Models.Reporter", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
